name: quizzapp
channels:
- conda-forge
- anaconda
dependencies:
- python=3.8
- psychopy=2022.2.5
- ffmpeg
- pip=23.2.1
- pyaudio
- pip:
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
  - websocket_client
  - pyinstaller==5.13.2
  - pydub==0.25.1
  - ffprobe